### ISSUE TITLE
网页版导出的规则没用

### ISSUE THREAD

**Issue by free-diy** [Adpro-Team/LTT2GKD#2]
[{"activityName":"com.yitong.mobile.biz.launcher.app.SplashActivity","className":"android.widget.Chronometer","clickable":true,"description":"0秒钟","idName":"com.srcb.pmbank:id/chronometer","onlyClick":false,"packageName":"com.srcb.pmbank","position":{"bottom":181,"left":1164,"right":1407,"top":80},"text":"跳过 3s"}]
上面规则转换gkd规则没用啊
{
  id: -2,
  name: '本地订阅',
  version: 0,
  author: 'gkd',
  globalGroups: [],
  categories: [],
  apps: [],
}

**Comment by adproqwq** [comment]
这根本不是李跳跳的规则
